screenshot_as_a_service: ./run_in.sh ../../screenshot-as-a-service ./start-app.sh
spotlight: ./run_in.sh ../../spotlight ./start-app.sh
backdrop_read: ./run_in.sh ../../backdrop ./start-app.sh read 3038
backdrop_write: ./run_in.sh ../../backdrop ./start-app.sh write 3039
backdrop_admin: ./run_in.sh ../../backdrop ./start-app.sh admin 3203
stagecraft: ./run_in.sh ../../stagecraft ./start-app.sh 3204
admin: ./run_in.sh ../../performanceplatform-admin ./start-app.sh 3070
