language: ruby
rvm:
  - 1.9.3
  - 2.1.1
before_install:
  - gem install puppet
  - gem install librarian-puppet
  - librarian-puppet install
script:
  - ./run_tests.sh
notifications:
  email: false
branches:
  except:
    - /^build_\d+$/
