language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
before_install:
  - gem install puppet
  - gem install librarian-puppet
  - librarian-puppet install
script:
  - ./run_tests.sh
notifications:
  email: false
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: 2.1.1
branches:
  except:
    - /^build_\d+$/
