---
domain_name: perfplat.dev
environment: development
ssl::params::ssl_path: '/etc/ssl'
ssl::params::ssl_cert_file: 'certs/ssl-cert-snakeoil.pem'
ssl::params::ssl_key_file: 'private/ssl-cert-snakeoil.key'
ufw_rules:
    allowsshfromanywhere:
        port: 22
        ip:   'any'

# TODO ensure whitelist_ips cascades down correctly from pp-deployment
whitelist_ips: 127.0.0.1
