---
domain_name: perfplat.dev
environment: development
ssl::params::ssl_path: '/etc/ssl'
ssl::params::ssl_cert_file: 'certs/ssl-cert-snakeoil.pem'
ssl::params::ssl_key_file: 'private/ssl-cert-snakeoil.key'
ufw_rules:
    allowsshfromanywhere:
        port: 22
        ip:   'any'
# add in whitelistips
# also add these to our repo in pp-deployment so we get a private version of this
# do in deployment, etc, so we pull down whitelist
# (DUN VIA JENKINS)
whitelist_ips: 127.0.0.1
