---
domain_name: development.performance.service.gov.uk
pp_environment: dev

ssl::params::ssl_path: '/etc/ssl'
ssl::params::ssl_cert_file: 'certs/ssl-cert-snakeoil.pem'
ssl::params::ssl_key_file: 'private/ssl-cert-snakeoil.key'
ufw_rules:
  allowsshfromanywhere:
    port: 22
    ip:   'any'

# modify in pp-deployment to add more
fail2ban::whitelist_ips: 127.0.0.1

rabbitmq_sensu_password: 'iP2O51333kzask7'

# Keep elasticsearch heapsize low in dev
performanceplatform::elasticsearch::heap_size: '256m'
performanceplatform::hosts::ip: "%{::ipaddress_eth1}"

postgresql::server::postgres_password: 'super secret password'
postgresql::server::listen_address: '0.0.0.0'
