---
# Verify this with: http://lint.travis-ci.org/
language: ruby
# Delete dependency locks for matrix builds.
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 1.8.7
  - 1.9.3
env:
  matrix:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
# Only notify for failed builds.
notifications:
  email:
    on_success: never
