#!/bin/bash

set -eu

pp() {
  local blue="\033[34m"
  local reset="\033[0m"
  while read line; do
    echo -e "${blue}[bootstrap]${reset} ${line}"
  done
}

quieten_sudo() {
  echo "--> Set root profile to quieten sudo tty message" | pp
  echo '[[ $(test -t 0) ]] && mesg n' > /root/.profile
}

set_uk_apt_sources() {
  echo "--> Set sources.list to gb and update apt cache" | pp
  sed -i 's|http://us|http://gb|' /etc/apt/sources.list
  apt-get update -qq
  apt-get install -qq python-software-properties curl 2>&1 | pp
  add-apt-repository -y ppa:gds/performance-platform 2>&1 | pp
  apt-get update -qq
}

check_ruby() {
  echo "--> Check for Ruby" | pp
  [[ $(dpkg -s ruby1.9.1 >/dev/null 2>&1) ]] || \
    apt-get install -qq ruby1.9.1 2>&1 | pp
}

check_bundler() {
  echo "--> Check for Bundler" | pp
  echo 'gem: --quiet --no-rdoc --no-ri' > /root/.gemrc
  # FIXME: bundler search -i doesn't say if something isn't installed
  local out=$(gem list bundler | grep bundler)
  [[ -n $out ]] || gem install bundler 2>&1 | pp
}

create_user() {
  echo "--> Creating user" | pp
  groupadd gds
  useradd -G gds -s /bin/bash -m $1
  mkdir /home/${1}/.ssh
  echo "ssh-rsa $2 ${1}_user" > /home/${1}/.ssh/authorized_keys
  chmod 700 /home/${1}/.ssh
  chmod 644 /home/${1}/.ssh/authorized_keys
  chown -R $1 /home/${1}/.ssh
  echo "%gds ALL=NOPASSWD:ALL" >/etc/sudoers.d/gds
  chmod 0440 /etc/sudoers.d/gds
}

main() {
  quieten_sudo
  set_uk_apt_sources
  check_ruby
  check_bundler
  create_user deploy 'DEPLOY PUBLIC KEY SHOULD GO HERE'
}

main

