screenshot_as_a_service: ./run_in.sh /var/apps/screenshot-as-a-service ./start-app.sh
spotlight: ./run_in.sh /var/apps/spotlight ./start-app.sh
backdrop_read: ./run_in.sh /var/apps/backdrop ./start-app.sh read 3038
backdrop_write: ./run_in.sh /var/apps/backdrop ./start-app.sh write 3039
backdrop_admin: ./run_in.sh /var/apps/backdrop ./start-app.sh admin 3203
stagecraft: ./run_in.sh /var/apps/stagecraft ./start-app.sh 3204
