#!/bin/bash
set -eu

cd "$(dirname $0)/.."
LOGFILE=/vagrant/puppet.log
if [ -e $LOGFILE ]; then
  rm $LOGFILE
fi
exec ./bin/puppet apply --modulepath=modules:vendor/modules \
                        --hiera_config=hiera.yaml \
			--logdest=console \
			--logdest=$LOGFILE \
			--verbose \
                        manifests
