#!/bin/sh -ex

THIS_SCRIPT=$(readlink -f $0)
THIS_DIR=$(dirname ${THIS_SCRIPT})

REPO_DIR=$(dirname ${THIS_DIR}/..)

function delete_ruby_bundles {
    rm -rf ${REPO_DIR}/vendor/bundle
}

function delete_puppet_modules {
    rm -rf ${REPO_DIR}/vendor/modules
}

function delete_librarian_cache {
    rm -rf ${REPO_DIR}/.tmp/librarian
}

function install_ruby_bundles {
    pushd ${REPO_DIR}
    bundle install --without NONEXISTENT
    popd
}

function install_puppet_modules {
    pushd ${REPO_DIR}
    bundle exec librarian-puppet install
    popd
}

delete_ruby_bundles
delete_puppet_modules
delete_librarian_cache

install_ruby_bundles
install_puppet_modules
